export const AppState = {
  activeTool: "SELECT",
  currentColor: "#000000",
  fillColor: "#cccccc", 
  useFill: false, 
  lineWidth: 2,
  lineStyle: "solid",
  isDrawing: false,
  clickCount: 0,
  startX: 0,
  startY: 0,
  lastX: 0,
  lastY: 0,
  shapes: [],
  selectedShape: null,
  undoStack: [],
  redoStack: [],
  bgImage: null,
};
